### ISSUE TITLE
Travis Broken - Attrs install

### ISSUE THREAD

**Issue by ghost** [open-contracting/lib-cove-ocds#10]
Latest Travis runs are broken because of a weird attrs install issue.

The latest version of jsonschema clearly specifies attrs>=17.4.0 https://github.com/Julian/jsonschema/blob/master/setup.cfg

In our Travis setup, we run `pip install -r requirements_dev.txt` - that specifies `-e .`, ie setup.py and that specifes `jsonschema`.

So I would assume that when pip was run, it would be smart enought to work out it needs attrs>=17.4.0. 

But No.

It says `Requirement already satisfied: attrs>=17.2.0 in /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (from pytest->-r requirements_dev.txt (line 4))`

And if you stick a `pip freeze` in it says the current version of attrs is 17.3.0

And then, not surprisingly, pytest crashes in a Jsonschema import `TypeError: attrib() got an unexpected keyword argument 'converter'`

Why, isn't pip getting a later version of attrs?  The (line 4)) is a clue - that line is the `pytest` line, not the `-e .` line. Also, it works fine on Python 3.5 (gets attrs 18.1.0, all works) - it only breaks on Python 3.6

???????????????????????????

**Comment by ghost** [comment]
Call with @kindly  - noted there are no req.in files - I'm going to try adding those
